#pragma once

namespace LastMusicPlayer::Backend::DatabaseAccountSchema
{
    inline constexpr char CreateTablesSql[] =
        "CREATE TABLE IF NOT EXISTS AccountProfiles ("
        "AccountId TEXT PRIMARY KEY,"
        "DisplayName TEXT,"
        "Username TEXT,"
        "AvatarUrl TEXT,"
        "PlanLabel TEXT,"
        "UpdatedAtUtc TEXT);"
        "CREATE TABLE IF NOT EXISTS AccountTracks ("
        "AccountId TEXT NOT NULL,"
        "RemoteId TEXT NOT NULL,"
        "SourceUrl TEXT,"
        "Title TEXT,"
        "Artist TEXT,"
        "Album TEXT,"
        "Genre TEXT,"
        "DurationSeconds REAL DEFAULT 0,"
        "ArtworkUrl TEXT,"
        "DateAddedSortKey REAL DEFAULT 0,"
        "DateAddedText TEXT,"
        "DurationText TEXT,"
        "IsLiked INTEGER DEFAULT 0,"
        "PlayCount INTEGER DEFAULT 0,"
        "FirstPlayedAtUtc TEXT,"
        "LastPlayedAtUtc TEXT,"
        "LastPositionSeconds REAL DEFAULT 0,"
        "UpdatedAtUtc TEXT,"
        "PRIMARY KEY (AccountId, RemoteId),"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS AccountPlaylists ("
        "AccountId TEXT NOT NULL,"
        "PlaylistId TEXT NOT NULL,"
        "Name TEXT,"
        "Description TEXT,"
        "SourceUrl TEXT,"
        "UpdatedAtUtc TEXT,"
        "PRIMARY KEY (AccountId, PlaylistId),"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS AccountPlaylistTracks ("
        "AccountId TEXT NOT NULL,"
        "PlaylistId TEXT NOT NULL,"
        "RemoteId TEXT NOT NULL,"
        "TrackOrder INTEGER NOT NULL DEFAULT 0,"
        "PRIMARY KEY (AccountId, PlaylistId, RemoteId),"
        "FOREIGN KEY (AccountId, PlaylistId) REFERENCES AccountPlaylists(AccountId, PlaylistId) ON DELETE CASCADE,"
        "FOREIGN KEY (AccountId, RemoteId) REFERENCES AccountTracks(AccountId, RemoteId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS PlaybackEvents ("
        "EventId TEXT PRIMARY KEY,"
        "AccountId TEXT NOT NULL,"
        "RemoteId TEXT NOT NULL,"
        "TrackJson TEXT NOT NULL,"
        "PlayedAtUtc TEXT NOT NULL,"
        "PositionSeconds REAL DEFAULT 0,"
        "AttemptCount INTEGER DEFAULT 0,"
        "LastAttemptAtUtc TEXT,"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS PendingLikes ("
        "AccountId TEXT NOT NULL,"
        "RemoteId TEXT NOT NULL,"
        "DesiredState INTEGER NOT NULL,"
        "TrackJson TEXT NOT NULL,"
        "UpdatedAtUtc TEXT NOT NULL,"
        "AttemptCount INTEGER DEFAULT 0,"
        "LastAttemptAtUtc TEXT,"
        "PRIMARY KEY (AccountId, RemoteId),"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS AccountSyncState ("
        "AccountId TEXT PRIMARY KEY,"
        "LastSuccessfulSyncUtc TEXT,"
        "LastSafeErrorCode TEXT,"
        "LegacyHistoryImportState TEXT,"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);"
        "CREATE TABLE IF NOT EXISTS ActiveAccountContext ("
        "SingletonId INTEGER PRIMARY KEY CHECK (SingletonId=1),"
        "RemoteMode TEXT NOT NULL DEFAULT 'LocalOnly',"
        "AccountId TEXT);"
        // The last catalog discovery payload that parsed into real shelves, so a
        // relaunch can draw them before the network answers. Stored raw and
        // re-parsed on read: the payload carries only titles, ids and artwork
        // URLs, so unlike the track tables there is no expiring credential in it
        // to strip. Keyed by region because the shelves differ per storefront,
        // and cascade-deleted with the profile so signing out drops it.
        "CREATE TABLE IF NOT EXISTS CatalogDiscoveryCache ("
        "AccountId TEXT NOT NULL,"
        "Storefront TEXT NOT NULL,"
        "Payload TEXT NOT NULL,"
        "FetchedAtUtc TEXT,"
        "PRIMARY KEY (AccountId, Storefront),"
        "FOREIGN KEY (AccountId) REFERENCES AccountProfiles(AccountId) ON DELETE CASCADE);";

    inline constexpr char RemoveLegacyGenericAccountTracksSql[] =
        "DELETE FROM Tracks WHERE SourceKind='remote' AND Provider='account';";
    inline constexpr char RemoveTransientRemoteUrlsSql[] =
        "UPDATE Tracks SET FilePath='' WHERE SourceKind='remote' AND COALESCE(FilePath,'')<>'';"
        "UPDATE Tracks SET SourceUrl='' WHERE SourceKind='remote' AND ("
        "lower(SourceUrl) LIKE '%token=%' OR lower(SourceUrl) LIKE '%signature=%' OR lower(SourceUrl) LIKE '%sig=%' OR "
        "lower(SourceUrl) LIKE '%credential=%' OR lower(SourceUrl) LIKE '%x-amz-%' OR lower(SourceUrl) LIKE '%x-goog-%' OR "
        "lower(SourceUrl) LIKE '%expires=%' OR lower(SourceUrl) LIKE '%api_key=%' OR lower(SourceUrl) LIKE '%apikey=%' OR "
        "lower(SourceUrl) LIKE '%session=%' OR lower(SourceUrl) LIKE '%bearer=%' OR lower(SourceUrl) LIKE '%password=%' OR "
        "lower(SourceUrl) LIKE '%jwt=%' OR lower(SourceUrl) LIKE '%auth=%' OR lower(SourceUrl) LIKE '%key=%');"
        "UPDATE Tracks SET ArtworkUrl='' WHERE SourceKind='remote' AND ("
        "lower(ArtworkUrl) LIKE '%token=%' OR lower(ArtworkUrl) LIKE '%signature=%' OR lower(ArtworkUrl) LIKE '%sig=%' OR "
        "lower(ArtworkUrl) LIKE '%credential=%' OR lower(ArtworkUrl) LIKE '%x-amz-%' OR lower(ArtworkUrl) LIKE '%x-goog-%' OR "
        "lower(ArtworkUrl) LIKE '%expires=%' OR lower(ArtworkUrl) LIKE '%api_key=%' OR lower(ArtworkUrl) LIKE '%apikey=%' OR "
        "lower(ArtworkUrl) LIKE '%session=%' OR lower(ArtworkUrl) LIKE '%bearer=%' OR lower(ArtworkUrl) LIKE '%password=%' OR "
        "lower(ArtworkUrl) LIKE '%jwt=%' OR lower(ArtworkUrl) LIKE '%auth=%' OR lower(ArtworkUrl) LIKE '%key=%');"
        "UPDATE Albums SET ArtworkUrl='' WHERE lower(ArtworkUrl) LIKE '%token=%' OR lower(ArtworkUrl) LIKE '%signature=%' OR "
        "lower(ArtworkUrl) LIKE '%credential=%' OR lower(ArtworkUrl) LIKE '%x-amz-%' OR lower(ArtworkUrl) LIKE '%x-goog-%' OR "
        "lower(ArtworkUrl) LIKE '%expires=%' OR lower(ArtworkUrl) LIKE '%api_key=%' OR lower(ArtworkUrl) LIKE '%session=%';"
        "UPDATE Playlists SET ArtworkUrl='' WHERE lower(ArtworkUrl) LIKE '%token=%' OR lower(ArtworkUrl) LIKE '%signature=%' OR "
        "lower(ArtworkUrl) LIKE '%credential=%' OR lower(ArtworkUrl) LIKE '%x-amz-%' OR lower(ArtworkUrl) LIKE '%x-goog-%' OR "
        "lower(ArtworkUrl) LIKE '%expires=%' OR lower(ArtworkUrl) LIKE '%api_key=%' OR lower(ArtworkUrl) LIKE '%session=%';"
        "UPDATE AccountTracks SET SourceUrl='' WHERE lower(SourceUrl) LIKE '%token=%' OR lower(SourceUrl) LIKE '%signature=%' OR "
        "lower(SourceUrl) LIKE '%credential=%' OR lower(SourceUrl) LIKE '%x-amz-%' OR lower(SourceUrl) LIKE '%x-goog-%' OR "
        "lower(SourceUrl) LIKE '%expires=%' OR lower(SourceUrl) LIKE '%api_key=%' OR lower(SourceUrl) LIKE '%session=%';"
        "UPDATE AccountTracks SET ArtworkUrl='' WHERE lower(ArtworkUrl) LIKE '%token=%' OR lower(ArtworkUrl) LIKE '%signature=%' OR "
        "lower(ArtworkUrl) LIKE '%credential=%' OR lower(ArtworkUrl) LIKE '%x-amz-%' OR lower(ArtworkUrl) LIKE '%x-goog-%' OR "
        "lower(ArtworkUrl) LIKE '%expires=%' OR lower(ArtworkUrl) LIKE '%api_key=%' OR lower(ArtworkUrl) LIKE '%session=%';"
        "UPDATE AccountProfiles SET AvatarUrl='' WHERE lower(AvatarUrl) LIKE '%token=%' OR lower(AvatarUrl) LIKE '%signature=%' OR "
        "lower(AvatarUrl) LIKE '%credential=%' OR lower(AvatarUrl) LIKE '%x-amz-%' OR lower(AvatarUrl) LIKE '%x-goog-%' OR "
        "lower(AvatarUrl) LIKE '%expires=%' OR lower(AvatarUrl) LIKE '%api_key=%' OR lower(AvatarUrl) LIKE '%session=%';"
        "UPDATE AccountPlaylists SET SourceUrl='' WHERE lower(SourceUrl) LIKE '%token=%' OR lower(SourceUrl) LIKE '%signature=%' OR "
        "lower(SourceUrl) LIKE '%credential=%' OR lower(SourceUrl) LIKE '%x-amz-%' OR lower(SourceUrl) LIKE '%x-goog-%' OR "
        "lower(SourceUrl) LIKE '%expires=%' OR lower(SourceUrl) LIKE '%api_key=%' OR lower(SourceUrl) LIKE '%session=%';";


    inline constexpr char CreateEffectiveTracksViewSql[] =
        "DROP VIEW IF EXISTS EffectiveTracks;"
        "CREATE VIEW EffectiveTracks AS "
        "SELECT t.Id, t.SourceKey, t.SourceKind, t.Provider, t.SourceUrl, t.FilePath, "
        "t.Title, t.Artist, t.Album, t.Genre, t.DurationSeconds, t.ArtworkUrl, "
        "t.DateAddedSortKey, t.DateAddedText, t.DurationText, t.PlayCount, "
        "t.LastPlayedOrder, t.IsLiked, t.IsActive, t.UpdatedAt, t.LastPlayed, t.RemoteId "
        "FROM Tracks t WHERE t.SourceKind<>'remote' OR EXISTS ("
        "SELECT 1 FROM ActiveAccountContext c WHERE c.SingletonId=1 AND c.RemoteMode='ApiKey') "
        "UNION ALL "
        "SELECT -a.rowid, 'account|' || a.AccountId || '|' || a.RemoteId, 'remote', 'account', "
        "a.SourceUrl, '', a.Title, a.Artist, a.Album, a.Genre, a.DurationSeconds, a.ArtworkUrl, "
        // An account track only carries a date of its own when the service sent
        // one, which it does not for anything picked up from the catalog: those
        // arrive with a zero key and so sorted as though they had never been
        // added, which emptied the Recently Added shelf for a library with no
        // local files. Fall back to when the track was first, then last, heard.
        // This is the same chain the web client uses: addedAt, firstPlayedAt,
        // lastPlayedAt, so both clients order the shelf alike.
        "CASE WHEN COALESCE(a.DateAddedSortKey,0)<>0 THEN a.DateAddedSortKey "
        "ELSE COALESCE(CAST(strftime('%s', a.FirstPlayedAtUtc) AS REAL), "
        "CAST(strftime('%s', a.LastPlayedAtUtc) AS REAL), 0) END, "
        "a.DateAddedText, a.DurationText, a.PlayCount, "
        "COALESCE(CAST(strftime('%s', a.LastPlayedAtUtc) AS INTEGER),0), a.IsLiked, 1, "
        "COALESCE(CAST(strftime('%s', a.UpdatedAtUtc) AS INTEGER),0), a.LastPlayedAtUtc, a.RemoteId "
        "FROM AccountTracks a JOIN ActiveAccountContext c ON c.SingletonId=1 AND c.RemoteMode='Account' AND c.AccountId=a.AccountId;";
}
